### ISSUE TITLE
Need a way to indicate which variables come from -v in awk source

### ISSUE THREAD

**Issue by glennj** [exercism/awk#104]
It's confusing to see variables just show up uninitialized in awk source files. "where did this thing come from"?

Perhaps maybe just a usage comment at the top of the file, like
```
# usage: gawk -f raindrops.awk -v num=3
```
So if I search for `num`, I'll see it there.

The gawk linter complains about this too, but I don't think there's anything to do be done about that.

**Comment by glennj** [comment]
At the moment, in the main branch:
```
all-your-base
anagram
armstrong-numbers
grep
kindergarten-garden
nth-prime
raindrops
robot-simulator
run-length-encoding
series
sum-of-multiples
triangle
```

**Comment by glennj** [comment]
How about a simple comment template to be placed in the exercise stub: using `all-your-base` as an example
```awk
# These variables are initialized on the command line (using '-v'):
# - ibase
# - obase
```

**Comment by IsaacG** [comment]
That sounds reasonably simple and clear to me. We could write an awk program to validate that the variables in the stub and in the tests line up :)
