### ISSUE TITLE
Circular Buffer

### ISSUE THREAD

**Issue by glennj** [exercism/awk#124]

**Comment by glennj** [comment]
Thinking a little harder about this, I don't know how to implement it. Consider a `read()` operation on a circular buffer
* if there is data in the buffer, return a value
* if the buffer is empty ... some exceptional condition

Only
* awk doesn't have exception, except for `exit`
* cannot return a _reference_ to a non-array

Possibilities
* return some sentinel value. Yuck. That prevents that value from actual being present in the buffer
* force the user to pass an array value that gets populated with a tuple: `[success_status, value]`
    * this is something that elixir does.
    * It would look like:
        ```awk
        # circular buffer `buff` is initialized, then:
        read(buff, result)
        if (result[1] == "ok")
            value = result[2]
        else if (result[1] == "err")
            die("buffer is empty")
        ```

**Comment by IsaacG** [comment]
The buffer supports a `full()` and `empty()` check. How bad would it be for a `read()` to `exit(1)` when the buffer is empty?

**Comment by glennj** [comment]
Hmm, that would satisfy the exercise, but a data structure that aborts my program ...

**Comment by IsaacG** [comment]
Yeah. It's not a pretty solution. Passing on this one might make sense.

**Comment by glennj** [comment]
I might play with it some more.

**Comment by glennj** [comment]
PR has been closed without merging
