### ISSUE TITLE
shebang is broken

### ISSUE THREAD

**Issue by IsaacG** [exercism/awk#158]
```bash
» head -n1 leap.awk
#!/usr/bin/env gawk -f
» chmod 755 leap.awk
» ./leap.awk <<< 2
/usr/bin/env: ‘gawk -f’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines

# Modified shebang:
» head -n1 leap.awk
#!/usr/bin/env -S gawk -f
» ./leap.awk <<< 2
false
```

The shebang `#!/usr/bin/env gawk -f` is completely broken. "According to POSIX, the hashbang can have one argument." (see [SO](https://stackoverflow.com/questions/733824/how-to-run-a-shell-script-on-a-unix-console-or-mac-terminal/733901#733901)).

Our options here are (1) hard code a `/usr/bin/gawk` path or (2) rely on GNU `env` and `-S` or (3) drop the shebang and not rely on it.

See also [Wikipedia](https://en.wikipedia.org/wiki/Shebang_(Unix)#Character_interpretation) and [netbsd mail list](http://mail-index.netbsd.org/netbsd-users/2008/11/09/msg002388.html)

@glennj Thoughts?

**Comment by glennj** [comment]
- MacOS `env` (not GNU) accepts `-S`
    - man env -> "The -P, -S and -v options were added in FreeBSD 6.0." 
- Busybox `env` does not.
    - `/usr/bin/env: unrecognized option: S`

Probably best to just drop it. Maybe document it ... somewhere.
