### ISSUE TITLE
Issue with one of the unit tests for AWK "all your base"

### ISSUE THREAD

**Issue by TheLinuxEnthusiast** [exercism/awk#204]
Hi,

One of the unit tests has the obase parameter in the wrong location:

@test 'output base is one' {
    [[ $BATS_RUN_SKIPPED == "true" ]] || skip
    run gawk -f all-your-base.awk -v ibase=2 1 <<< "1 0 1 0 1 -v obase=0"
    assert_failure
    assert_output    # there is _some_ output
}

It should be changed to the following:

@test 'output base is one' {
    [[ $BATS_RUN_SKIPPED == "true" ]] || skip
    run gawk -f all-your-base.awk -v ibase=2 obase=1 <<< "1 0 1 0 1"
    assert_failure
    assert_output    # there is _some_ output
}

Otherwise the test won't run.

Darren Foley

**Comment by glennj** [comment]
Thanks for pointing this out.

Pedantically, it does run and it (should) output the right error message:
```
$ gawk -f all-your-base.awk -v ibase=2 1 <<< "1 0 1 0 1 -v obase=0"
:0: assertion failed: Output base must be greater than one
```
`1` is a valid awk program. It is, I think, executing the `-f` code _first_ before running the "1" code.
