### ISSUE TITLE
Add icon for “Automated readability index”

### ISSUE THREAD

**Issue by rabestro** [exercism/awk#207]
I suggest adding an icon for the exercise "Automated readability index".

I am attaching one of the possible options for the icon.

![Clock4](https://github.com/exercism/awk/assets/52966251/e73f5ed8-6203-4f6d-b15a-0414ef8d9e6a)

**Comment by glennj** [comment]
Hey, thanks for finding this. Exercise icons live in the exercism/website-icons repo.
