### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by iHiD** [exercism/awk#282]
@rabestro You have qualified to be a maintainer here. Thank you for your hard work! Would you like to join?

**Comment by rabestro** [comment]
> @rabestro You have qualified to be a maintainer here. Thank you for your hard work! Would you like to join?

Hi Jeremy, Thank you for your invitation. I would be glad if I could help the community. 
I would like to understand better what is expected of me. What tasks are the highest priority in your opinion?

**Comment by iHiD** [comment]
@rabestro Great!

There's information here on maintainer roles in general: https://exercism.org/docs/community/maintainers

But really it gives you more power over what is merged into the repo. You can review and merge other people's contributions. As AWK already has two senior maintainers in Glenn and Issac, the work is shared, and you'll probably be guided by them. It also elevates your voice so that you can sort of assert stronger opinions and people know you've earned the right to be listened to.

In terms of priorities, I'd leave @glennj or @IsaacG to answer if there are any specific improvements to AWK that we should be looking at next.

You should receive an invite to join the org and the team now. You'll also get access to the #maintainers channel on Discord if your Exercism and Discord accounts [are linked](https://exercism.org/settings/integrations).

Thanks again!

**Comment by glennj** [comment]
Welcome @rabestro !
