### ISSUE TITLE
Compile a list of Concepts

### ISSUE THREAD

**Issue by glennj** [exercism/awk#9]
This will help to provide focus for deciding which exercises to implement.

**Comment by glennj** [comment]
Refer to the TODO file in https://github.com/exercism/awk/tree/main/concepts

**Comment by IsaacG** [comment]
@glennj Is there anything remaining for this issue which isn't covered by the TODO?

**Comment by kytrinyx** [comment]
One thing that I would recommend is to not worry about making the concept list exhaustive up front, but rather look at the 5 or so simplest practice exercises, and then identify (some of) concepts that are used. From there the concept list tends to grow organically as we work on concept exercises.

Once there's a WIP concept exercise implementation we generally recommend doing a gut check: are there any concepts that need to be covered as a prerequisite to this exercise? And then those can be added to the list.

**Comment by glennj** [comment]
@IsaacG nope.

@kytrinyx thank you, great advice
